<?php

namespace common\modules\tehnic\models;

use common\models\query\CustomerQuery;
use fbalabanov\filekit\behaviors\UploadBehavior;
use Yii;
use dsx90\launcher\models\Launch;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "{{%tehnic_cat}}".
 *
 * @property integer $launch_id
 * @property string $content
 * @property string $thumbnail
 * @property string $thumbnail_base_url
 * @property string $thumbnail_path
 *
 * @property Launch $launch
 */
class TehnicCat extends ActiveRecord
{
    public $thumbnail;
    public $option;
    public $scale;
    public $category;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%tehnic_cat}}';
    }

    public function behaviors()
    {
        return [
            [
                'class' => UploadBehavior::className(),
                'attribute' => 'thumbnail',
                'pathAttribute' => 'thumbnail_path',
                'baseUrlAttribute' => 'thumbnail_base_url'
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['launch_id'], 'integer'],
            [['content'], 'string'],
            [['thumbnail_base_url', 'thumbnail_path'], 'string', 'max' => 255],
            [['launch_id'], 'unique'],
            [['launch_id'], 'exist', 'skipOnError' => true, 'targetClass' => Launch::className(), 'targetAttribute' => ['launch_id' => 'id']],
            [['thumbnail', 'option', 'scale', 'category'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'launch_id'             => Yii::t('common', 'Launch ID'),
            'content'               => Yii::t('common', 'Content'),
            'thumbnail'             => Yii::t('common', 'Thumbnail'),
            'thumbnail_base_url'    => Yii::t('common', 'Thumbnail Base Url'),
            'thumbnail_path'        => Yii::t('common', 'Thumbnail Path'),
            'option'                => Yii::t('common', 'Options'),
            'category'              => Yii::t('common', 'Category Assignment'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLaunch()
    {
        return $this->hasOne(Launch::className(), ['id' => 'launch_id']);
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOptionAssignment()
    {
        return $this->hasMany(TehnicOptionAssignment::className(), ['category_id' => 'launch_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOptions()
    {
        return $this->hasMany(TehnicOption::className(), ['option_id' => 'option_id'])->via('optionAssignment');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAssignment()
    {
        return $this->hasMany(TehnicCatAssignment::className(), ['category' => 'launch_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function beforeDelete()
    {
        if(parent::beforeDelete()){
            TehnicOptionAssignment::deleteAll(['id'=>$this->launch_id]);
            return true;
        } else {
            return false;
        }
    }

    public function afterFind()
    {
        $this->option = ArrayHelper::map($this->options, 'option_id', 'option');
        $this->scale = ArrayHelper::map($this->options, 'option_id', 'scale');
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        if(is_array($this->option)){
            $arr = ArrayHelper::map($this->options, 'option','option_id');
            foreach ($this->option as $one){
                if(isset($arr[$one])){
                    unset($arr[$one]);
                } else {
                    $this->createNewOption($one);
                }
            }
            TehnicOptionAssignment::deleteAll(['and',['category_id'=>$this->launch_id], ['option_id'=>$arr]]); // Удаление опции в связи
        } else {
            TehnicOptionAssignment::deleteAll(['category_id'=>$this->launch_id]);
        }
    }
    private function createNewOption($new_option){
        if(!$option = TehnicOption::find()->andWhere(['option'=>$new_option])->one()){
            $option = new TehnicOption();
            $option->option = $new_option;
            if(!$option->save()){
                $option = null;
            }
        }
        if ($option instanceof TehnicOption){
            $assignment = new TehnicOptionAssignment();
            $assignment->category_id = $this->launch_id;
            $assignment->option_id = $option->option_id;
            if($assignment->save())
                return $assignment->option_id;
        }
        return false;
    }

    /**
     * @inheritdoc
     * @return CustomerQuery the active query used by this AR class.//
     */
    public static function find()
    {
        return new \common\models\query\CustomerQuery(get_called_class());
    }
}
