<?php

namespace backend\widgets;

use yii\jui\Widget;

class AdverWidget extends Widget
{
    public $title;
    public $longtitle;
    public $description;
    public $slug;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        isset($this->title) ? $this->title : $this->title = 'Титул';
        isset($this->longtitle) ? $this->longtitle : $this->longtitle ='Краткое описание';
        isset($this->description) ? $this->description : $this->description = 'Обьявление';
        isset($this->slug) ? $this->slug : $this->slug = 'url ссылка';

    }

    public function run()
    {
        return $this->render('adver',[
        ]);
    }
}